export const sampleTasks = [
  {
    title: 'Clean garage',
    details: 'through out garbage, sweep floor, clean ',
    completed: false,
    priority: '3',
    contact: 'Person 1',
    dueDate: '5/10/23',
    id: '1',
  },
  {
    title: 'Pay bills',
    details: 'give away all of my money',
    completed: true,
    priority: '1',
    contact: 'Person 2',
    dueDate: '5/10/23',
    id: '2',
  },
  {
    title: 'Read a book',
    details: 'learn something interesting',
    completed: false,
    priority: '2',
    contact: 'Person 1',
    dueDate: '7/11/23',
    id: '3',
  },
  {
    title: 'Build a project',
    details: 'make a cool app',
    completed: true,
    priority: '2',
    contact: 'Person 9',
    dueDate: '5/12/23',
    id: '4',
  },
  {
    title: 'Fix bugs',
    details: 'review unintentional behavior in the app',
    completed: false,
    priority: '3',
    contact: 'Person 3',
    dueDate: '1/10/25',
    id: '5',
  },
]

export const sampleContacts = [
  {
    first_name: 'Person 1',
    last_name: 'LastName 1',
    dob: '01/01/1990',
    category: 'client',
    phone: '(509) 555-6677',
    email: 'person@email.com',
    position: 'Student',
    organization: 'College University',
    about:
      'Incididunt magna tempor aliqua Lorem cupidatat dolore velit exercitation proident in exercitation eu proident culpa. Velit esse dolore pariatur sint esse dolor eu pariatur tempor tempor. Commodo consectetur mollit do pariatur duis adipisicing incididunt aute reprehenderit et anim. Tempor ipsum esse exercitation aliquip enim est occaecat. Minim qui dolore voluptate enim consectetur nulla mollit pariatur laborum anim minim sunt. Duis laborum ipsum ex aliquip anim dolore incididunt sint pariatur fugiat magna.',
    address: '123 fake St.',
    city: 'Real City',
    state: 'WA',
    zip_code: '99001',
    id: '1',
    imageUrl:
      'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
  },
  {
    first_name: 'Person 2',
    last_name: 'LastName 2',
    dob: '01/01/1990',
    category: 'prospect',
    phone: '(509) 555-6677',
    email: 'person@email.com',
    position: 'Worker',
    organization: 'Mega Corp',
    about:
      'Irure sunt velit ex ullamco occaecat esse quis enim adipisicing enim. Deserunt laborum dolor occaecat in enim cupidatat anim sint laboris do. Culpa ipsum labore do quis magna do occaecat incididunt ea exercitation est enim consectetur labore.',
    address: '123 fake St.',
    city: 'Sandpoint',
    state: 'Idaho',
    zip_code: '99001',
    id: '2',
    imageUrl:
      'https://images.unsplash.com/photo-1517365830460-955ce3ccd263?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
  },
  {
    first_name: 'Person 3',
    last_name: 'LastName 3',
    dob: '01/01/1990',
    category: 'prospect',
    phone: '(509) 555-6677',
    email: 'person@email.com',
    position: 'Supervisor',
    organization: 'Mega Corp',
    about:
      'Non mollit proident reprehenderit velit sunt magna cillum sit dolore ea pariatur velit. Aute eu voluptate fugiat aliqua nostrud velit culpa veniam occaecat consectetur aute ad. Mollit dolor nulla ut culpa id enim cupidatat aliqua Lorem. Occaecat do in consequat excepteur est dolore. Reprehenderit elit labore duis occaecat anim sunt qui laborum laborum in dolor veniam cillum cupidatat. Ut non esse irure id reprehenderit minim adipisicing velit quis excepteur duis occaecat.',
    address: '123 fake St.',
    city: 'Seattle',
    state: 'WA',
    zip_code: '99001',
    id: '3',
    imageUrl:
      'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
  },
  {
    first_name: 'Person 4',
    last_name: 'LastName 4',
    dob: '01/01/1990',
    category: 'client',
    phone: '(509) 555-6677',
    email: 'person@email.com',
    position: 'Worker',
    organization: 'Mini Corp',
    about:
      'Deserunt fugiat aliquip enim adipisicing enim in culpa. Nulla anim mollit deserunt veniam cillum labore sunt excepteur reprehenderit. Dolor ullamco sit consectetur laborum labore ut aliquip ut magna id minim nisi fugiat labore. Commodo commodo culpa velit quis ea non ipsum occaecat sint. Laborum culpa reprehenderit magna cillum.',
    address: '123 fake St.',
    city: 'Portland',
    state: 'OR',
    zip_code: '99001',
    id: '4',
    imageUrl:
      'https://images.unsplash.com/photo-1517365830460-955ce3ccd263?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
  },
  {
    first_name: 'Person 5',
    last_name: 'LastName 5',
    dob: '03/01/1966',
    category: 'vender',
    phone: '(509) 555-6677',
    email: 'person@email.com',
    position: 'Contractor',
    organization: 'FedEx',
    about:
      'Nisi laborum amet non proident ea. Consequat laborum voluptate ipsum officia labore ullamco esse. Sint quis ad pariatur id sunt cupidatat labore do. Excepteur aute est anim velit elit ut mollit sunt in fugiat. Anim adipisicing qui labore ea sunt elit anim.',
    address: '123 fake St.',
    city: 'Real City',
    state: 'WA',
    zip_code: '99001',
    id: '5',
    imageUrl:
      'https://images.unsplash.com/photo-1517365830460-955ce3ccd263?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
  },
  {
    first_name: 'Person 6',
    last_name: 'LastName 6',
    dob: '01/01/1990',
    category: 'client',
    phone: '(509) 555-6677',
    email: 'person@email.com',
    position: 'Worker',
    organization: 'Work Inc.',
    about:
      'Ullamco cupidatat veniam anim anim dolore sunt cupidatat. Sit nostrud ullamco aliquip occaecat. Dolore aliqua ex occaecat et esse ipsum et aute elit dolor tempor.',
    address: '123 fake St.',
    city: 'Real City',
    state: 'WA',
    zip_code: '99001',
    id: '6',
    imageUrl:
      'https://images.unsplash.com/photo-1500917293891-ef795e70e1f6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
  },
  {
    first_name: 'Person 7',
    last_name: 'LastName 7',
    dob: '01/01/1990',
    category: 'vender',
    phone: '(509) 555-6677',
    email: 'person@email.com',
    position: 'Dealer',
    organization: 'Car Lot',
    about:
      'Consequat sint proident amet irure sunt cillum aute aliquip. Consequat anim culpa veniam eu veniam incididunt nulla in veniam adipisicing id. Magna voluptate irure voluptate dolore officia. Ipsum ex incididunt enim deserunt aliqua deserunt amet elit. Exercitation magna fugiat pariatur proident non elit do aliqua velit laboris. Tempor esse aliqua id non velit laborum pariatur labore ut non duis et. Aliqua voluptate qui excepteur aliqua cupidatat irure nisi et enim mollit dolore.',
    address: '123 fake St.',
    city: 'Real City',
    state: 'WA',
    zip_code: '99001',
    id: '7',
    imageUrl:
      'https://images.unsplash.com/photo-1517365830460-955ce3ccd263?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
  },
  {
    first_name: 'Person 8',
    last_name: 'LastName 8',
    dob: '01/01/1990',
    category: 'client',
    phone: '(509) 555-6677',
    email: 'person@email.com',
    position: 'Worker',
    organization: 'Mega Corp',
    about:
      'Sit pariatur consequat in in enim ut minim. Est minim occaecat dolor ipsum excepteur esse irure ullamco. Mollit aute laboris est Lorem fugiat. Do laboris nulla eu quis ullamco deserunt Lorem velit consectetur ut quis labore est.',
    address: '123 fake St.',
    city: 'Real City',
    state: 'WA',
    zip_code: '99001',
    id: '8',
    imageUrl:
      'https://images.unsplash.com/photo-1500917293891-ef795e70e1f6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
  },

  {
    first_name: 'Person 9',
    last_name: 'LastName 9',
    dob: '01/01/1990',
    category: 'client',
    phone: '(509) 555-6677',
    email: 'person@email.com',
    position: 'Advisor',
    organization: 'FBI',
    about:
      'Nulla anim ad nulla ullamco consequat dolore officia adipisicing commodo esse reprehenderit aliquip dolor. Labore consectetur minim nulla labore deserunt ex cillum fugiat non officia duis dolor est velit. Id ipsum magna officia labore ipsum Lorem ea excepteur incididunt ut enim veniam. Deserunt sint amet exercitation eiusmod occaecat consequat proident cupidatat. Do velit velit irure irure et velit et amet fugiat exercitation. Duis proident cupidatat laboris labore labore occaecat occaecat proident sunt ex ipsum mollit. Adipisicing ea in ea eu ullamco minim exercitation.',
    address: '123 fake St.',
    city: 'Where',
    state: 'TX',
    zip_code: '88220',
    id: '9',
    imageUrl:
      'https://images.unsplash.com/photo-1505840717430-882ce147ef2d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
  },
  {
    first_name: 'Person 10',
    last_name: 'LastName 10',
    dob: '01/01/1990',
    category: 'client',
    phone: '(509) 555-6677',
    email: 'person@email.com',
    position: 'Agent',
    organization: 'Super Secret Agents',
    about:
      'Id nostrud sunt ex enim do eu officia proident sunt commodo officia aute ullamco. Proident consectetur occaecat ipsum anim est nulla quis voluptate exercitation veniam aliqua ea ipsum eiusmod. Non sit mollit veniam duis in nisi pariatur velit elit non sint sit. In sit commodo consequat magna elit laboris. Et cillum sint in sunt sunt in dolor veniam nulla aliquip qui aliquip culpa ut. Ipsum nulla reprehenderit est nisi veniam. Nostrud nulla velit adipisicing commodo amet ipsum ullamco commodo pariatur.',
    address: '123 fake St.',
    city: 'Real City',
    state: 'WA',
    zip_code: '99001',
    id: '10',
    imageUrl:
      'https://images.unsplash.com/photo-1502685104226-ee32379fefbe?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
  },
  {
    first_name: 'Person 11',
    last_name: 'LastName 11',
    dob: '01/01/1990',
    category: 'client',
    phone: '(509) 555-6677',
    email: 'person@email.com',
    position: 'Programmer',
    organization: 'Codelots',
    about: '',
    address: '123 fake St.',
    city: 'Real City',
    state: 'WA',
    zip_code: '99001',
    id: '11',
    imageUrl:
      'https://images.unsplash.com/photo-1505840717430-882ce147ef2d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
  },
]

export const sampleNotes = [
  {
    title: "Last week's meeting",
    details:
      'Ea reprehenderit duis quis excepteur aliquip incididunt minim reprehenderit. Mollit reprehenderit sit culpa irure laboris anim deserunt enim adipisicing consectetur dolor reprehenderit labore. Magna dolor Lorem exercitation ex culpa in cupidatat eu Lorem in dolor et nulla.',
    category: 'Meetings',
    created_at: 'January 21, 1922',
    updated_at: 'August 1, 2020',
    contact_id: '2',
    id: '1',
  },
  {
    title: 'Birthday',
    details:
      'Consectetur dolore enim deserunt sunt pariatur deserunt dolor irure. Mollit laboris occaecat sint non exercitation occaecat amet do velit duis aliqua reprehenderit. Anim irure nostrud tempor tempor nostrud nisi mollit veniam mollit ad do minim. Enim eu sit aliqua culpa voluptate sint. Cillum duis aliqua non elit dolor dolore aute officia ex ea. Proident id minim culpa excepteur dolor commodo magna. Occaecat et incididunt ut Lorem voluptate sit minim sit incididunt cillum sunt officia.',
    category: 'Events',
    created_at: 'September 1, 1994',
    updated_at: 'May 16, 2023',
    contact_id: '4',
    id: '2',
  },
  {
    title: 'Go to school',
    details:
      'Duis amet fugiat ut nostrud reprehenderit minim non. Labore fugiat sit in est culpa exercitation eu dolor. Culpa reprehenderit nisi deserunt exercitation esse sint velit aliquip laborum do amet labore enim consequat. Ipsum quis occaecat pariatur exercitation proident dolore officia dolor aliquip pariatur exercitation dolor voluptate exercitation. Voluptate et ullamco laborum ullamco excepteur elit dolor exercitation officia esse. Elit labore dolor consequat aliquip est laboris commodo qui ut. Eiusmod cupidatat non dolor anim nulla nostrud qui veniam ullamco deserunt sit officia.',
    category: 'Events',
    created_at: 'January 21, 2023',
    updated_at: 'August 19, 2023',
    contact_id: '8',
    id: '3',
  },
  {
    title: 'Always do that',
    details:
      'Aute velit dolore commodo aute enim eiusmod ut Lorem amet Lorem. Et est est ut commodo aliqua. Consequat occaecat proident magna consequat eu et enim magna duis commodo aliquip labore tempor. Ipsum elit in nisi do consectetur minim ullamco qui est et nulla ea occaecat et. Ad voluptate sunt sint laboris ut irure aliquip ad ad ipsum esse ex.',
    category: 'Advice',
    created_at: 'January 21, 1922',
    updated_at: 'August 1, 2020',
    contact_id: '1`',
    id: '4',
  },
  {
    title: 'Never do this',
    details:
      'Ipsum ex consectetur in officia dolore in in ea aliqua enim cillum cillum. Sunt culpa consequat ea duis adipisicing deserunt dolor esse cillum in labore in. Velit ullamco aliqua nulla ullamco. Ut velit reprehenderit laboris culpa laboris aliquip qui dolore. Occaecat est irure laborum adipisicing sunt aliquip. Consectetur dolor laboris non id veniam in reprehenderit mollit officia qui voluptate commodo sunt. Nulla mollit do voluptate pariatur duis id laborum aliquip consequat ex elit eiusmod sit adipisicing.',
    category: 'Advice',
    created_at: 'February, 2022',
    updated_at: 'August 1, 2022',
    contact_id: '3',
    id: '5',
  },
  {
    title: 'How to do something',
    details:
      'Tempor magna nostrud dolore laboris minim sint nostrud ad duis eu quis. Proident dolore tempor ullamco culpa laborum mollit id magna velit esse qui. Do id deserunt in officia adipisicing et aute. Cupidatat et deserunt reprehenderit culpa nostrud pariatur id qui est ea. Exercitation minim labore adipisicing consequat quis. Exercitation et do velit qui ad adipisicing aliqua veniam sunt velit elit cupidatat.',
    category: 'Meetings',
    created_at: 'December 8, 1999',
    updated_at: 'August 12, 2019',
    contact_id: '2',
    id: '6',
  },
]
