export const sampleTasks = [
  {
    title: 'Clean garage',
    details: 'through out garbage, sweep floor, clean ',
    completed: false,
    priority: '3',
    contact: 'Person 1',
    dueDate: '5/10/23',
    id: '1',
  },
  {
    title: 'Pay bills',
    details: 'give away all of my money',
    completed: true,
    priority: '1',
    contact: 'Person 2',
    dueDate: '5/10/23',
    id: '2',
  },
  {
    title: 'Read a book',
    details: 'learn something interesting',
    completed: false,
    priority: '2',
    contact: 'Person 1',
    dueDate: '7/11/23',
    id: '3',
  },
  {
    title: 'Build a project',
    details: 'make a cool app',
    completed: true,
    priority: '2',
    contact: 'Person 9',
    dueDate: '5/12/23',
    id: '4',
  },
  {
    title: 'Fix bugs',
    details: 'review unintentional behavior in the app',
    completed: false,
    priority: '3',
    contact: 'Person 3',
    dueDate: '1/10/25',
    id: '5',
  },
]

export const sampleContacts = [
  {
    first_name: 'Person 1',
    last_name: 'LastName 1',
    dob: '01/01/1990',
    category: 'client',
    phone: '(509) 555-6677',
    email: 'person@email.com',
    address: '123 fake St.',
    city: 'Real City',
    state: 'Washington',
    zip_code: '99001',
    id: '1',
    imageUrl:
      'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
  },
  {
    first_name: 'Person 2',
    last_name: 'LastName 2',
    dob: '01/01/1990',
    category: 'prospect',
    phone: '(509) 555-6677',
    email: 'person@email.com',
    address: '123 fake St.',
    city: 'Sandpoint',
    state: 'Idaho',
    zip_code: '99001',
    id: '2',
    imageUrl:
      'https://images.unsplash.com/photo-1517365830460-955ce3ccd263?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
  },
  {
    first_name: 'Person 3',
    last_name: 'LastName 3',
    dob: '01/01/1990',
    category: 'prospect',
    phone: '(509) 555-6677',
    email: 'person@email.com',
    address: '123 fake St.',
    city: 'Seattle',
    state: 'Washington',
    zip_code: '99001',
    id: '3',
    imageUrl:
      'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
  },
  {
    first_name: 'Person 4',
    last_name: 'LastName 4',
    dob: '01/01/1990',
    category: 'client',
    phone: '(509) 555-6677',
    email: 'person@email.com',
    address: '123 fake St.',
    city: 'Portland',
    state: 'Oregon',
    zip_code: '99001',
    id: '4',
    imageUrl:
      'https://images.unsplash.com/photo-1517365830460-955ce3ccd263?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
  },
  {
    first_name: 'Person 5',
    last_name: 'LastName 5',
    dob: '03/01/1966',
    category: 'vender',
    phone: '(509) 555-6677',
    email: 'person@email.com',
    address: '123 fake St.',
    city: 'Real City',
    state: 'Washington',
    zip_code: '99001',
    id: '5',
    imageUrl:
      'https://images.unsplash.com/photo-1517365830460-955ce3ccd263?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
  },
  {
    first_name: 'Person 6',
    last_name: 'LastName 6',
    dob: '01/01/1990',
    category: 'client',
    phone: '(509) 555-6677',
    email: 'person@email.com',
    address: '123 fake St.',
    city: 'Real City',
    state: 'Washington',
    zip_code: '99001',
    id: '6',
    imageUrl:
      'https://images.unsplash.com/photo-1500917293891-ef795e70e1f6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
  },
  {
    first_name: 'Person 7',
    last_name: 'LastName 7',
    dob: '01/01/1990',
    category: 'vender',
    phone: '(509) 555-6677',
    email: 'person@email.com',
    address: '123 fake St.',
    city: 'Real City',
    state: 'Washington',
    zip_code: '99001',
    id: '7',
    imageUrl:
      'https://images.unsplash.com/photo-1517365830460-955ce3ccd263?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
  },
  {
    first_name: 'Person 8',
    last_name: 'LastName 8',
    dob: '01/01/1990',
    category: 'client',
    phone: '(509) 555-6677',
    email: 'person@email.com',
    address: '123 fake St.',
    city: 'Real City',
    state: 'Washington',
    zip_code: '99001',
    id: '8',
    imageUrl:
      'https://images.unsplash.com/photo-1500917293891-ef795e70e1f6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
  },

  {
    first_name: 'Person 9',
    last_name: 'LastName 9',
    dob: '01/01/1990',
    category: 'client',
    phone: '(509) 555-6677',
    email: 'person@email.com',
    address: '123 fake St.',
    city: 'Where',
    state: 'Texas',
    zip_code: '88220',
    id: '9',
    imageUrl:
      'https://images.unsplash.com/photo-1505840717430-882ce147ef2d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
  },
  {
    first_name: 'Person 10',
    last_name: 'LastName 10',
    dob: '01/01/1990',
    category: 'client',
    phone: '(509) 555-6677',
    email: 'person@email.com',
    address: '123 fake St.',
    city: 'Real City',
    state: 'Washington',
    zip_code: '99001',
    id: '10',
    imageUrl:
      'https://images.unsplash.com/photo-1502685104226-ee32379fefbe?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
  },
  {
    first_name: 'Person 11',
    last_name: 'LastName 11',
    dob: '01/01/1990',
    category: 'client',
    phone: '(509) 555-6677',
    email: 'person@email.com',
    address: '123 fake St.',
    city: 'Real City',
    state: 'Washington',
    zip_code: '99001',
    id: '11',
    imageUrl:
      'https://images.unsplash.com/photo-1505840717430-882ce147ef2d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
  },
]

export const sampleNotes = [
  {
    title: "Last week's meeting",
    details: 'Ea reprehenderit duis quis excepteur aliquip incididunt minim reprehenderit. Mollit reprehenderit sit culpa irure laboris anim deserunt enim adipisicing consectetur dolor reprehenderit labore. Magna dolor Lorem exercitation ex culpa in cupidatat eu Lorem in dolor et nulla.',
    category: 'Meetings',
    created_at: 'January 21, 1922',
    updated_at: 'August 1, 2020',
    contact_id: '2',
    id: '1',
  },
  {
    title: 'Birthday',
    details: 'Consectetur dolore enim deserunt sunt pariatur deserunt dolor irure. Mollit laboris occaecat sint non exercitation occaecat amet do velit duis aliqua reprehenderit. Anim irure nostrud tempor tempor nostrud nisi mollit veniam mollit ad do minim. Enim eu sit aliqua culpa voluptate sint. Cillum duis aliqua non elit dolor dolore aute officia ex ea. Proident id minim culpa excepteur dolor commodo magna. Occaecat et incididunt ut Lorem voluptate sit minim sit incididunt cillum sunt officia.',
    category: 'Events',
    created_at: 'September 1, 1994',
    updated_at: 'May 16, 2023',
    contact_id: '4',
    id: '2',
  },
  {
    title: 'Go to school',
    details: 'Duis amet fugiat ut nostrud reprehenderit minim non. Labore fugiat sit in est culpa exercitation eu dolor. Culpa reprehenderit nisi deserunt exercitation esse sint velit aliquip laborum do amet labore enim consequat. Ipsum quis occaecat pariatur exercitation proident dolore officia dolor aliquip pariatur exercitation dolor voluptate exercitation. Voluptate et ullamco laborum ullamco excepteur elit dolor exercitation officia esse. Elit labore dolor consequat aliquip est laboris commodo qui ut. Eiusmod cupidatat non dolor anim nulla nostrud qui veniam ullamco deserunt sit officia.',
    category: 'Events',
    created_at: 'January 21, 2023',
    updated_at: 'August 19, 2023',
    contact_id: '8',
    id: '3',
  },
  {
    title: 'Always do that',
    details: 'Aute velit dolore commodo aute enim eiusmod ut Lorem amet Lorem. Et est est ut commodo aliqua. Consequat occaecat proident magna consequat eu et enim magna duis commodo aliquip labore tempor. Ipsum elit in nisi do consectetur minim ullamco qui est et nulla ea occaecat et. Ad voluptate sunt sint laboris ut irure aliquip ad ad ipsum esse ex.',
    category: 'Advice',
    created_at: 'January 21, 1922',
    updated_at: 'August 1, 2020',
    contact_id: '1`',
    id: '4',
  },
  {
    title: 'Never do this',
    details: 'Ipsum ex consectetur in officia dolore in in ea aliqua enim cillum cillum. Sunt culpa consequat ea duis adipisicing deserunt dolor esse cillum in labore in. Velit ullamco aliqua nulla ullamco. Ut velit reprehenderit laboris culpa laboris aliquip qui dolore. Occaecat est irure laborum adipisicing sunt aliquip. Consectetur dolor laboris non id veniam in reprehenderit mollit officia qui voluptate commodo sunt. Nulla mollit do voluptate pariatur duis id laborum aliquip consequat ex elit eiusmod sit adipisicing.',
    category: 'Advice',
    created_at: 'February, 2022',
    updated_at: 'August 1, 2022',
    contact_id: '3',
    id: '5',
  },
  {
    title: 'How to do something',
    details:
      'Tempor magna nostrud dolore laboris minim sint nostrud ad duis eu quis. Proident dolore tempor ullamco culpa laborum mollit id magna velit esse qui. Do id deserunt in officia adipisicing et aute. Cupidatat et deserunt reprehenderit culpa nostrud pariatur id qui est ea. Exercitation minim labore adipisicing consequat quis. Exercitation et do velit qui ad adipisicing aliqua veniam sunt velit elit cupidatat.',
    category: 'Meetings',
    created_at: 'December 8, 1999',
    updated_at: 'August 12, 2019',
    contact_id: '2',
    id: '6',
  },
]
